CREATE TABLE `permission`
(
    `id`    BIGINT(20) NOT NULL AUTO_INCREMENT,
    `name`  VARCHAR(255) NOT NULL,
    `label` VARCHAR(255) NOT NULL,
    PRIMARY KEY (`id`)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;